--- 
title: "Наука о данных для Цифровых гуманитарных исследований в R"
author: "Г. А. Мороз"
bibliography:
- bibliography.bib
editor_options:
  chunk_output_type: console
link-citations: yes
documentclass: book
site: bookdown::bookdown_site
biblio-style: apalike
---

# Введение

## Установка R и RStudio

В данной книге используется исключительно R [@r_core_team19], так что для занятий понадобятся:

* R ([можно скачать здесь](https://www.r-project.org/))
* RStudio --- IDE для R ([можно скачать здесь](https://www.rstudio.com/products/rstudio/download/))
* и некоторые пакеты на R

Часто можно увидеть или услышать, что R --- язык программирования для "статистической обработки данных". Изначально это, конечно, было правдой, но уже давно R --- это полноценный язык программирования, который при помощи своих пакетом позволяет решать огромный спектр задач. В данной книге используются следующая версия R:

```{r}
sessionInfo()$R.version$version.string
```

Некоторые люди не любят устанавливать лишние программы себе на компьютер, несколько вариантов есть и для них:

* [RStudio cloud](https://rstudio.cloud/) --- полная функциональность RStudio, пока бесплатная, но скоро это исправят;
* [RStudio on rollApp](https://www.rollapp.com/app/rstudio) --- облачная среда, позволяющая разворачивать программы.
  
## Полезные ссылки

В интернете легко найти документацию и туториалы по самым разным вопросам в R, так что главный залог успеха --- грамматно пользоваться поисковиком, и лучше на английском языке.

* [книга [@wickham16]](https://r4ds.had.co.nz/) является достаточно сильной альтернативой всему курсу
* [stackoverflow](https://stackoverflow.com) --- сервис, где достаточно быстро отвечают на любые вопросы (не обязательно по R)
* [RStudio community](https://community.rstudio.com/) --- быстро отвечают на вопросы, связанные с R
* [русский stackoverflow](https://ru.stackoverflow.com)
* [R-bloggers](https://www.r-bloggers.com/) --- сайт, где собираются новинки, связанные с R
* [чат](https://t.me/rlang_ru), где можно спрашивать про R на русском (но почитайте [правила чата](https://github.com/r-lang-group-ru/group-rules/blob/master/README.md), перед тем как спрашивать)
* [чат](https://t.me/joinchat/CxZg5goGc6rlWGjcvOYrpA) по визуализации данных, [чат](https://t.me/ddjrus) датажурналистов
* [канал про визуализацию ](https://t.me/chartomojka), [дата-блог "Новой газеты"](https://t.me/novaya_data), ...